export const RPC_ACCOUNTS_SERVICE = "RPC_ACCOUNTS_SERVICE";
export const RPC_WALLETS_SERVICE = "RPC_WALLETS_SERVICE";
export const RPC_FX_SERVICE = "RPC_FX_SERVICE";
export const RPC_TRANSACTION_SERVICE = "RPC_TRANSACTION_SERVICE";
